compiler = "gyc"
license = "GPL-v3"
authors = ["Emile Cadorel <ecadorel@gmail.com>"]
type = "executable"
libraries = ["gmp", "mpfr"]
description = "Ymir language server"
version = "0.1.0"
name = "ymir-lsp"

[registry]
git = "git@github.com:GNU-Ymir/ymir-lsp.git"

[dependencies.ymirc]
version = "1.10.3"
url = "git:https://github.com/GNU-Ymir/bootstrap.git"
